#!/bin/sh

set -e

: ${PROVIDER=csi}
: ${EXTSTORAGE=/usr/share/ganeti/extstorage}

LIBDIR=@LIBDIR@

PROVIDERDIR=${EXTSTORAGE}/${PROVIDER}
CONFDIR=/etc/ganeti-extstorage-csi
ENVFILE="${CONFDIR}/${PROVIDER}.env"

if [ -d "${PROVIDERDIR}" ]; then
    echo "It seems that external provider ${PROVIDER} already exists in ${PROVIDERDIR}"
    exit 1
fi

mkdir -p ${PROVIDERDIR} ${CONFDIR}

cat > ${PROVIDERDIR}/wrapper <<EOF
#!/bin/sh

# load environment
. ${ENVFILE}

export OPERATION="\$(basename "\$0")"

exec ${LIBDIR}/ganeti-extstorage-csi
EOF
touch ${PROVIDERDIR}/parameters.list

if ! [ -f "${ENVFILE}" ]; then
	cat > "${ENVFILE}" <<EOF
## -- shell fragment --
# Sample environment file for ganeti-extstorage-csi
# These are defaults
#export CSI_ENDPOINT=unix:///csi/csi.sock
#export CSI_ENDPOINT=127.0.0.1:5001

# CSI TLS parameters. CSI_TLS_CERT and CSI_TLS_KEY are mandatory for TLS.
# If CSI_TLS_CA is given, the server is required to present a valid certificate
# against the CA. This is HIGHLY RECOMMENDED.
#export CSI_TLS_CERT=/path/to/cert.pem
#export CSI_TLS_KEY=/path/to/key.pem
#export CSI_TLS_CA=/path/to/ca.pem

# Default config uses etcd at localhost:2379 for metadata store.
# An etcd cluster needs to be set up on all nodes beforehand
#export ETCD_STORE_ENDPOINT=localhost:2379

# Etcd TLS parameters. ETCD_TLS_CERT and ETCD_TLS_KEY are mandatory for TLS.
# If ETCD_TLS_CA is given, the server is required to present a valid certificate
# against the CA. This is HIGHLY RECOMMENDED.
#export ETCD_TLS_CERT=/path/to/cert.pem
#export ETCD_TLS_KEY=/path/to/key.pem
#export ETCD_TLS_CA=/path/to/ca.pem

# For development, you may set a file-based storage.
# Enabling it disables the etcd store. This is really just for development.
#export FILE_STORE_BASE=/var/lib/ganeti-extstorage-csi/${PROVIDER}

EOF
fi

chmod 755 ${PROVIDERDIR}/wrapper

for cmd in attach create detach grow remove setinfo verify ; do
    ln -s wrapper ${PROVIDERDIR}/${cmd}
done

echo "+ Ganeti-extstorage provider has been installed, name=${PROVIDER}, dir=${PROVIDERDIR}"
echo "+ Dont forget to edit ${PROVIDERDIR}/parameters.list"
