#!/bin/sh

set -e

: ${PROVIDER=csi}
: ${EXTSTORAGE=/usr/share/ganeti/extstorage}

LIBDIR=@LIBDIR@

PROVIDERDIR=${EXTSTORAGE}/${PROVIDER}

if [ -d "${PROVIDERDIR}" ]; then
    echo "It seems that external provider ${PROVIDER} already exists in ${PROVIDERDIR}"
    exit 1
fi

mkdir -p ${PROVIDERDIR}

cat > ${PROVIDERDIR}/wrapper <<EOF
#!/bin/sh

# load environment
. ${PROVIDERDIR}/env

export OPERATION="\$(basename "\$0")"

exec ${LIBDIR}/ganeti-extstorage-csi
EOF
touch ${PROVIDERDIR}/parameters.list

cat > ${PROVIDERDIR}/env <<EOF
## -- shell fragment --
# Sample environment file for ganeti-extstorage-csi
# These are defaults
#export CSI_ENDPOINT=unix:///csi/csi.sock
#export CSI_ENDPOINT=127.0.0.1:5001

# Default config uses etcd at http://localhost:2379 for metadata store.
# An etcd cluster needs to be set up on all nodes beforehand
#export ETCD_STORE_ENDPOINT=http://localhost:2379

# For development, you may set a file-based storage.
# Enabling it disables the etcd store. This is really just for development.
#export FILE_STORE_BASE=/var/lib/ganeti-extstorage-csi/${PROVIDER}

# TLS parameters. TLS_CERT and TLS_KEY are mandatory for TLS. If TLS_CA is given, the client
# is required to present a certificate and be valid against the CA. This is HIGHLY RECOMMENDED.
#export TLS_CERT=/path/to/cert.pem
#export TLS_KEY=/path/to/key.pem
#export TLS_CA=/path/to/ca.pem
EOF

chmod 755 ${PROVIDERDIR}/wrapper

for cmd in attach create detach grow remove setinfo verify ; do
    ln -s wrapper ${PROVIDERDIR}/${cmd}
done

echo "+ Ganeti-extstorage provider has been installed, name=${PROVIDER}, dir=${PROVIDERDIR}"
echo "+ Dont forget to edit ${PROVIDERDIR}/parameters.list"
